spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/charityBook
    username: postgres
    password: CharityBook123!
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        hbm2ddl:
          auto: update
    generate-ddl: true
  flyway:
    user: postgres
    password: CharityBook123!
    url: jdbc:postgresql://localhost:5433/charityBook
    enabled: false
server:
  port: 8080
  servlet:
    context-path: /